name: Bootstrap Terraform Backend

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

on:
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run bootstrap script
        run: bash .github/workflows/bootstrap-backend.sh