name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - Dev
          - Test
          - Main

permissions:
  id-token: write
  contents: read

env:
  location: westeurope
  environment: ${{ github.event.inputs.environment || 'Dev' }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: Destroy Azure Resources
    environment: ${{ github.event.inputs.environment || 'Dev' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/Terraform
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          ENV_LOWER=$(echo "$environment" | tr '[:upper:]' '[:lower:]')
          terraform init \
            -backend-config="resource_group_name=Homelab-management-RG" \
            -backend-config="storage_account_name=tfstatehomelabfozzen" \
            -backend-config="container_name=tfstate-$ENV_LOWER" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="use_oidc=true"

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var location=$location -var environment=$environment