name: 'Terraform Deployment'

on:
  push:
    branches:
      - Dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - Dev
          - Test
          - Main

permissions:
  id-token: write
  contents: read

env:
    location: westeurope
    environment: ${{ github.event.inputs.environment || 'Dev' }}
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
        name: Deploy to Azure
        environment: ${{ github.event.inputs.environment || 'Dev' }}
        runs-on: ubuntu-latest
        # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
        defaults:
          run:
            working-directory: .github/Terraform
            shell: bash

        steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3

        # Install the latest version of Terraform CLI 
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        # note, env lower is only becasue the branch is uppercase...
        - name: Terraform Init
          run: |
            ENV_LOWER=$(echo "$environment" | tr '[:upper:]' '[:lower:]')
            terraform init \
              -backend-config="resource_group_name=Homelab-management-RG" \
              -backend-config="storage_account_name=tfstatehomelabfozzen" \
              -backend-config="container_name=tfstate-$ENV_LOWER" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="use_oidc=true"


        - name: Terraform Format
          run: terraform fmt -recursive

        # Validate before Planning
        - name: Terraform Validate
          run: terraform validate 

        # Generates an execution plan for Terraform
        - name: Terraform Plan
          run: terraform plan -input=false -var location=$location -var environment=$environment

        - name: Terraform Apply
          run: terraform apply -auto-approve -input=false -var location=$location -var environment=$environment